# GLOBAL SITE SETTINGS

# General
seo_title: "Wilckens Roche"
title: "Wilckens Roche Lawyers"
company: "Wilckens Roche PTY LTD"
description: "Wilckens Roche is Williamstown's oldest law firm and one of the oldest law firms in the western suburbs of Melbourne. A quality-assured incorporated legal practice, call us now."

# Contact Info
email: info@wrl.com.au
phone: (03) 8383 5999
fax: (03) 8383 5900
address: "43 Ferguson Street Williamstown VIC 3016"
address_multiline: "43 Ferguson Street<br>Williamstown VIC 3016"
dx: "DX 16101, Williamstown"
pobox: "P.O. Box 18<br>Williamstown VIC 3016"

# Social Networks
facebook: "http://www.facebook.com/pages/Wilckens-Roche-Lawyers/193138314034665"
twitter: "https://twitter.com/#!/WilckensRoche"
linkedin: "http://www.linkedin.com/company/2491031?goback=%2Efcs_GLHD_wilckens+roche_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&trk=ncsrch_hits"

# Google Map
google_map: ""

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"